# Generated by Django 5.0.6 on 2025-09-08 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weightage', models.DecimalField(decimal_places=2, help_text='Weightage in percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('exam_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('venue', models.CharField(max_length=200)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.course')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='examinations.examtype')),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2)),
                ('is_pass', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_results', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.examschedule')),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('student', 'exam_schedule')},
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='question_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=False)),
                ('exam_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_paper', to='examinations.examschedule')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_question_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RevaluationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('fee_paid', models.BooleanField(default=False)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluation_requests', to='examinations.examresult')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_revaluations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('absent', 'Absent'), ('present', 'Present')], default='registered', max_length=20)),
                ('seat_number', models.CharField(blank=True, max_length=20)),
                ('hall_ticket_number', models.CharField(blank=True, max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to=settings.AUTH_USER_MODEL)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='examinations.examschedule')),
            ],
            options={
                'ordering': ['-registration_date'],
                'unique_together': {('student', 'exam_schedule')},
            },
        ),
        migrations.CreateModel(
            name='ExamAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attendance', to=settings.AUTH_USER_MODEL)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='examinations.examschedule')),
            ],
            options={
                'ordering': ['-check_in_time'],
                'unique_together': {('student', 'exam_schedule')},
            },
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='answer_sheets/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_late_submission', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to=settings.AUTH_USER_MODEL)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to='examinations.examschedule')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'exam_schedule')},
            },
        ),
    ]
