# Generated by Django 5.2.6 on 2025-09-22 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('total_rooms', models.IntegerField()),
                ('capacity_per_room', models.IntegerField()),
                ('amenities', models.TextField(blank=True)),
                ('warden_name', models.CharField(max_length=100)),
                ('warden_contact', models.CharField(max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostelComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('mess', 'Mess'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hostels.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_contact', models.CharField(max_length=20)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messes', to='hostels.hostel')),
            ],
            options={
                'ordering': ['hostel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='hostels.mess')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad')], max_length=10)),
                ('floor', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostels.hostel')),
            ],
            options={
                'ordering': ['hostel', 'room_number'],
                'unique_together': {('hostel', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='HostelAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('remarks', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allotments', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='hostels.room')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('items', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='hostels.mess')),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
                'unique_together': {('mess', 'date', 'meal_type')},
            },
        ),
    ]
