# Generated by Django 5.0.6 on 2025-09-08 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('model_number', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=200)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('out_of_order', 'Out of Order')], default='available', max_length=20)),
                ('maintenance_schedule', models.TextField(blank=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('funded', 'Funded'), ('unfunded', 'Unfunded'), ('collaborative', 'Collaborative'), ('student', 'Student Project')], max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='proposed', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('funding_agency', models.CharField(blank=True, max_length=200)),
                ('grant_number', models.CharField(blank=True, max_length=100)),
                ('objectives', models.TextField()),
                ('methodology', models.TextField()),
                ('expected_outcomes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_investigators', models.ManyToManyField(blank=True, related_name='co_investigated_projects', to=settings.AUTH_USER_MODEL)),
                ('principal_investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_projects', to=settings.AUTH_USER_MODEL)),
                ('research_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='research.researcharea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('deliverables', models.TextField(blank=True)),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_milestones', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='research.researchproject')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ResearchGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_title', models.CharField(max_length=300)),
                ('funding_agency', models.CharField(max_length=200)),
                ('grant_number', models.CharField(max_length=100, unique=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('application_date', models.DateField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed')], default='applied', max_length=20)),
                ('application_document', models.FileField(blank=True, null=True, upload_to='grant_applications/')),
                ('approval_document', models.FileField(blank=True, null=True, upload_to='grant_approvals/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='research.researchproject')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='ResearchCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator_name', models.CharField(max_length=200)),
                ('collaborator_type', models.CharField(choices=[('academic', 'Academic'), ('industry', 'Industry'), ('government', 'Government'), ('international', 'International')], max_length=20)),
                ('institution', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('collaboration_start_date', models.DateField()),
                ('collaboration_end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='collaboration_agreements/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='research.researchproject')),
            ],
            options={
                'ordering': ['-collaboration_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(help_text='Comma-separated list of authors')),
                ('publication_type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book'), ('book_chapter', 'Book Chapter'), ('patent', 'Patent'), ('report', 'Technical Report')], max_length=20)),
                ('journal_name', models.CharField(blank=True, max_length=300)),
                ('conference_name', models.CharField(blank=True, max_length=300)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField()),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('issue', models.CharField(blank=True, max_length=20)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('issn', models.CharField(blank=True, max_length=20)),
                ('abstract', models.TextField()),
                ('keywords', models.TextField(help_text='Comma-separated keywords')),
                ('document', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_publications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='research.researchproject')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='ResearchStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('phd', 'PhD'), ('mtech', 'M.Tech'), ('msc', 'M.Sc'), ('btech', 'B.Tech'), ('intern', 'Intern')], max_length=10)),
                ('enrollment_date', models.DateField()),
                ('expected_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('thesis_title', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(default='active', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_students', to='research.researchproject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_students', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'project')},
            },
        ),
    ]
